# Generated by Django 5.0.3 on 2024-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("code", models.CharField(max_length=6)),
            ],
            options={
                "verbose_name": "Подтверждение номера телефона",
                "verbose_name_plural": "Подтверждения номеров телефонов",
            },
        ),
    ]
