# Generated by Django 5.0.3 on 2024-03-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_phoneconfirmation"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneconfirmation",
            name="sha256",
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
