# Generated by Django 5.0.3 on 2024-03-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_phoneconfirmation_sha256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneconfirmation",
            name="sha256",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
