# Generated by Django 5.0.3 on 2024-03-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_phoneconfirmation_sha256"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phoneconfirmation",
            name="sha256",
        ),
        migrations.AddField(
            model_name="phoneconfirmation",
            name="phone_hash",
            field=models.CharField(default=1, max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
