# Generated by Django 5.0.3 on 2024-03-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_phoneconfirmation_sha256_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneconfirmation",
            name="password",
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
