# Generated by Django 5.0.3 on 2024-03-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_phoneconfirmation_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneconfirmation",
            name="sent_time",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
