# Generated by Django 5.0.3 on 2024-03-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_phoneconfirmation_sent_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="phoneconfirmation",
            name="phone",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
