# Generated by Django 5.0.3 on 2024-03-27 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_customuser_phone_alter_phoneconfirmation_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[django.core.validators.RegexValidator("\\+?[78]\\d{10}")],
                verbose_name="Номер телефона",
            ),
        ),
    ]
