version: "3.9"

services:
  pgdb:
    container_name: pg_deliverympa
    image: postgres:16
    env_file:
      - .env
    volumes:
      - ~/.pg/pd_data/delivery-mpa:/var/lib/postgresql/data

  backend:
    container_name: backend_deliverympa
    build: 
      dockerfile: ./Dockerfile
      context: ./backend
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - pgdb
    volumes:
      - static_volume:/backend/static
      - media_volume:/backend/media

  nginx:
    container_name: nginx_deliverympa
    build:
      context: ./docker/nginx/
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - static_volume:/backend/static
      - media_volume:/backend/media
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
