version: "3.9"

services:
  pgdb:
    container_name: pg_deliverympa
    image: postgres:16
    env_file:
      - .env
    volumes:
      - /var/delivery-mpa/pg_data:/var/lib/postgresql/data
    restart: unless-stoped

  redis:
    container_name: rd_deliverympa
    image: redis:7.2
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD}"
    volumes:
      - /var/delivery-mpa/redis_data:/var/lib/redis/data
    ports:
      - "6379:6379"
    restart: unless-stoped

  backend:
    container_name: backend_deliverympa
    build: 
      dockerfile: ./Dockerfile
      context: ./backend
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - pgdb
      - redis
    volumes:
      - /var/delivery-mpa/static:/backend/static
      - /var/delivery-mpa/media:/backend/media
    restart: unless-stoped

  nginx:
    container_name: nginx_deliverympa
    build:
      context: ./docker/nginx/
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - /var/delivery-mpa/static:/backend/static
      - /var/delivery-mpa/media:/backend/media
      - /var/delivery-mpa/nginx-certs:/etc/nginx/certs/
    ports:
      - "${NGINX_HTTP_EXTERNAL_PORT}:80"
      - "${NGINX_HTTPS_EXTERNAL_PORT}:443"
    restart: unless-stoped
