# Generated by Django 5.0.3 on 2024-03-27 14:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0005_alter_characteristics_quantity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Уникальный идентификатор заказа",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator("\\+?[78]\\d{10}")
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Фамилия (необязательно)",
                    ),
                ),
                ("address", models.CharField(verbose_name="Адрес")),
                (
                    "delivery",
                    models.CharField(
                        choices=[("PK", "Самовывоз"), ("DL", "Доставка")],
                        max_length=2,
                        verbose_name="Метод доставки",
                    ),
                ),
                (
                    "payment",
                    models.CharField(
                        choices=[("CH", "Оплата наличными"), ("CD", "Оплата картой")],
                        max_length=2,
                        verbose_name="Способ оплаты",
                    ),
                ),
                (
                    "client_comment",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Комментарий клиента (необязательно)",
                    ),
                ),
                (
                    "business_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий компании"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PD", "Заказ ожидает подтверждения."),
                            ("PR", "Заказ готовится."),
                            ("RD", "Заказ готов. Ожидает доставки."),
                            ("OW", "Заказ в пути."),
                            ("DN", "Заказ полностью выполнен."),
                            ("DC", "Заказ отклонен."),
                        ],
                        default="PD",
                        max_length=2,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время последнего обновления"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Аккаунт заказчика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="products.unit",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["-created"], name="orders_orde_created_743fca_idx"
            ),
        ),
    ]
