# Generated by Django 5.0.3 on 2024-03-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0005_alter_characteristics_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(default="Самовывоз", verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.unit"
            ),
        ),
    ]
