# Generated by Django 5.0.3 on 2024-06-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_order_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payed_online",
            field=models.BooleanField(default=False, verbose_name="Оплачен онлайн"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.CharField(
                choices=[
                    ("CH", "Оплата наличными"),
                    ("CD", "Оплата картой"),
                    ("ON", "Оплата онлайн"),
                ],
                max_length=2,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
