# Generated by Django 5.0.3 on 2024-06-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_rename_payed_online_order_paid_online_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма оплаты"
            ),
        ),
    ]
