# Generated by Django 5.0.3 on 2024-03-22 12:50

import django.core.validators
import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="Название")),
                ("symbol", models.CharField()),
            ],
            options={
                "verbose_name": "Единица измерения",
                "verbose_name_plural": "Единицы измерения",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="По умолчанию 0. Максимальный приоритет 100.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Приоритет не может быть меньше нуля!"
                            ),
                            django.core.validators.MaxValueValidator(
                                100, "Приоритет не может быть больше 100!"
                            ),
                        ],
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Должен быть на английском!",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9-_%]+$", "Должен быть на английском!"
                            )
                        ],
                        verbose_name="Человекочитаемый URL",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_filename,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="categories.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступно"),
                ),
                ("name", models.CharField(unique=True, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Цена должна быть >= 1"
                            )
                        ],
                        verbose_name="Цена товарной единицы",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "Цена должна быть >= 1"
                            )
                        ],
                        verbose_name="Цена товарной единицы со скидкой",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товарная единица",
                "verbose_name_plural": "Товарные единицы",
            },
        ),
        migrations.CreateModel(
            name="Characteristics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measure_count",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Количество в заданных единицах измерения",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1, verbose_name="Количества товара в упаковке, шт"
                    ),
                ),
                (
                    "proteins",
                    models.IntegerField(blank=True, null=True, verbose_name="Белки"),
                ),
                (
                    "fats",
                    models.IntegerField(blank=True, null=True, verbose_name="Жиры"),
                ),
                (
                    "carbohydrates",
                    models.IntegerField(blank=True, null=True, verbose_name="Углеводы"),
                ),
                (
                    "kilocalories",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Килокалории"
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.measure",
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.unit",
                        verbose_name="Товарная единица",
                    ),
                ),
            ],
            options={
                "verbose_name": "Характеристика товарной единицы",
                "verbose_name_plural": "Характеристики товарных единиц",
            },
        ),
    ]
