# Generated by Django 5.0.3 on 2024-03-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(blank=True, null=True, verbose_name="Название"),
        ),
    ]
