# Generated by Django 5.0.3 on 2024-03-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
    ]
