# Generated by Django 5.0.3 on 2024-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_unit_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteristics",
            name="quantity",
            field=models.IntegerField(
                default=1, verbose_name="Количества штук в упаковке, шт"
            ),
        ),
    ]
