# Generated by Django 5.0.3 on 2024-04-03 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_characteristics_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characteristics",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="charcs",
                to="products.unit",
                verbose_name="Товарная единица",
            ),
        ),
    ]
