# Generated by Django 5.0.3 on 2024-03-22 12:50

import django.core.validators
import django.db.models.deletion
import utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступно"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="По умолчанию 0. Максимальный приоритет 100.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Приоритет не может быть меньше нуля!"
                            ),
                            django.core.validators.MaxValueValidator(
                                100, "Приоритет не может быть больше 100!"
                            ),
                        ],
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_filename,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Должен быть на английском!",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9-_%]+$", "Должен быть на английском!"
                            )
                        ],
                        verbose_name="Человекочитаемый URL",
                    ),
                ),
                (
                    "show_navbar",
                    models.BooleanField(
                        default=True, verbose_name="Отображать в навигационной панели"
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_filename,
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промо-категория",
                "verbose_name_plural": "Промо-категории",
            },
        ),
        migrations.CreateModel(
            name="PromoAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступно"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="По умолчанию 0. Максимальный приоритет 100.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Приоритет не может быть меньше нуля!"
                            ),
                            django.core.validators.MaxValueValidator(
                                100, "Приоритет не может быть больше 100!"
                            ),
                        ],
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Должен быть на английском!",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9-_%]+$", "Должен быть на английском!"
                            )
                        ],
                        verbose_name="Человекочитаемый URL",
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_filename,
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "straight_redirect",
                    models.BooleanField(
                        default=False,
                        verbose_name="Прямой переход на акционный товар или категорию",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "promotion_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotion.promotioncategory",
                        verbose_name="Промо-категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промо-акция",
                "verbose_name_plural": "Промо-акции",
            },
        ),
        migrations.CreateModel(
            name="ProductPromotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "promotion_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promotion.promotioncategory",
                        verbose_name="Промо-категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Промо-акция продукта",
                "verbose_name_plural": "Промо-акции продукта",
            },
        ),
    ]
