# Generated by Django 5.0.3 on 2024-03-24 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productpromotion",
            options={
                "verbose_name": "Промо-категория товара",
                "verbose_name_plural": "Промо-категории товара",
            },
        ),
    ]
