# Generated by Django 5.0.3 on 2024-03-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_unit_product"),
        ("promotion", "0002_alter_productpromotion_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpromotion",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_promotions",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
        migrations.AlterField(
            model_name="productpromotion",
            name="promotion_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_promotions",
                to="promotion.promotioncategory",
                verbose_name="Промо-категория",
            ),
        ),
    ]
