# Generated by Django 5.0.3 on 2024-04-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotion", "0003_alter_productpromotion_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpromotion",
            name="promotion_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_category",
                to="promotion.promotioncategory",
                verbose_name="Промо-категория",
            ),
        ),
    ]
