# Generated by Django 5.0.3 on 2024-03-22 12:50

import django.core.validators
import utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Доступно"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="По умолчанию 0. Максимальный приоритет 100.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Приоритет не может быть меньше нуля!"
                            ),
                            django.core.validators.MaxValueValidator(
                                100, "Приоритет не может быть больше 100!"
                            ),
                        ],
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_filename,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Должен быть на английском!",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9-_%]+$", "Должен быть на английском!"
                            )
                        ],
                        verbose_name="Человекочитаемый URL",
                    ),
                ),
                (
                    "show_navbar",
                    models.BooleanField(
                        default=True, verbose_name="Отображать в навигационной панели"
                    ),
                ),
                ("name", models.CharField(unique=True, verbose_name="Название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=utils.image_filename,
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
