# Generated by Django 5.0.3 on 2024-03-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_unit_product"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttag",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_tags",
                to="products.product",
                verbose_name="Товар",
            ),
        ),
    ]
